import { chromium } from 'playwright';
const b=await chromium.launch();
const ctx=await b.newContext({viewport:{width:1280,height:900}}); const p=await ctx.newPage();
await p.goto('http://localhost:4321/website/',{waitUntil:'load'}); await p.waitForTimeout(1000);
console.log('  my accordion divider:', await p.$eval('.service',e=>getComputedStyle(e).borderTopColor));
console.log('  my footer link:', await p.$eval('.site-footer__nav a',e=>{const c=getComputedStyle(e);
  return `fs=${c.fontSize} lh=${c.lineHeight} h=${Math.round(e.getBoundingClientRect().height)}`;}));
console.log('  --lh-footer-link resolves to:', await p.evaluate(()=>getComputedStyle(document.documentElement).getPropertyValue('--lh-footer-link')));
console.log('  my progress bar width:', await p.$eval('.sectors__progress',e=>getComputedStyle(e).width));
console.log('  my footer mark visible at 375?');
await ctx.close();
const c2=await b.newContext({viewport:{width:375,height:812}}); const p2=await c2.newPage();
await p2.goto('http://localhost:4321/website/',{waitUntil:'load'}); await p2.waitForTimeout(800);
console.log('     mark display:', await p2.$eval('.site-footer__mark',e=>getComputedStyle(e).display));
await b.close();
