import { chromium } from 'playwright';
const b=await chromium.launch();
const ctx=await b.newContext({viewport:{width:1280,height:900}}); const p=await ctx.newPage();
const errs=[]; p.on('console',m=>{if(m.type()==='error')errs.push(m.text());});
await p.goto('http://localhost:4321/website/',{waitUntil:'load'}); await p.waitForTimeout(1200);
const link=await p.$('.site-footer__totop');
console.log('link exists:', !!link);
console.log('href:', await p.$eval('.site-footer__totop',e=>e.getAttribute('href')));
console.log('aria-label:', await p.$eval('.site-footer__totop',e=>e.getAttribute('aria-label')));
console.log('#top target:', await p.evaluate(()=>{const t=document.getElementById('top');
  return t? `${t.tagName}#${t.id} offsetTop=${t.offsetTop}` : 'MISSING';}));
// scroll to the bottom, click it, confirm we return to the top
await p.evaluate(()=>window.scrollTo(0,document.body.scrollHeight));
await p.waitForTimeout(700);
const before=await p.evaluate(()=>Math.round(window.scrollY));
await p.$eval('.site-footer__totop',e=>e.click());
await p.waitForTimeout(1800);
const after=await p.evaluate(()=>Math.round(window.scrollY));
console.log(`scrollY: before=${before} -> after=${after}  ${after===0?'OK (returned to top)':'NOT at top'}`);
console.log('mark anim:', await p.$eval('.site-footer__mark',e=>{const c=getComputedStyle(e);
  return `${c.animationName}/${c.animationDuration}/${c.animationIterationCount}`;}));
console.log('errors:', errs.length?errs.slice(0,3):'none');
await b.close();
